apiVersion: extensions/v1beta1
kind: ReplicationController
metadata:
  name: randomReplicationContoller
  namespaces: dev
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app : dev 
    spec:
      containers:
      - name: nginx1
        image: nginx
        port : 
        - containerPort: 80 
