kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: vsan-storage-class
provisioner: kubernetes.io/vsphere-volume
parameters:
  diskformat: thin
  hostFailuresToTolerate: "1"
  diskStripes: "2"
  cacheReservation: "20"
  datastore: VSANDatastore
