apiVersion: extensions/v1beta1
kind: ReplicationController
metadata:
  name: randomreplicationcontoller
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app : dev 
    spec:
      containers:
      - name: nginx1
        image: nginx
        ports : 
        - containerPort: 80 
