apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name : randomreplicaset
  
  labels: 
    env: dev
    role: web
spec: 
  replicas: 3
  selector: 
    matchLabels:
      role: web
  template: 
    metadata: 
      labels: 
        role: web
  spec:
    containers: 
    - name: nginx
      image: nginx
      ports: 
      - containerPort: 80 
